### ISSUE TITLE
Unable to configure handler u'magicsHandler': u'home_path'

### ISSUE THREAD

**Issue by thomasgirault** [jupyter-incubator/sparkmagic#266]
I try to test sparkmagic with a miniconda2 env. 
However, the PySpark kernel doesn't start because the home_path magicHandler is not correctly configured :

> [I 12:11:31.571 NotebookApp] Kernel started: 6488e134-bfc8-4fa6-b117-e47fc029609f
Traceback (most recent call last):
  File "/home/tgirault/bin/miniconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/tgirault/bin/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/sparkmagic/kernels/pysparkkernel/pysparkkernel.py", line 28, in <module>
    IPKernelApp.launch_instance(kernel_class=PySparkKernel)
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-136>", line 2, in initialize
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/sparkmagic/kernels/pysparkkernel/pysparkkernel.py", line 23, in __init__
    language_info, session_language, **kwargs)
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/sparkmagic/kernels/wrapperkernel/sparkkernelbase.py", line 29, in __init__
    self.logger = SparkLog(u"{}_jupyter_kernel".format(self.session_language))
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/sparkmagic/utils/sparklogger.py", line 10, in __init__
    super(SparkLog, self).__init__(MAGICS_LOGGER_NAME, conf.logging_config(), class_name)
  File "/home/tgirault/bin/miniconda2/lib/python2.7/site-packages/hdijupyterutils/log.py", line 13, in __init__
    logging.config.dictConfig(logging_config)
  File "/home/tgirault/bin/miniconda2/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/home/tgirault/bin/miniconda2/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler u'magicsHandler': u'home_path'

**Comment by thomasgirault** [comment]
In the following config file, removing the magicsHandler section seemed to solve the problem. :
https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/example_config.json

**Comment by msftristew** [comment]
There shouldn't be a problem with the example_config.  How are you installing sparkmagic? Do you have the most recent version of everything?

**Comment by aggFTW** [comment]
Sorry for the inconvenience this caused. Fixing it with the PR I just opened.

Please treat that config file as overrides to the defaults.

Again, sorry for our mistake.
