### ISSUE TITLE
[Question]  ModuleNotFoundError when enabling the serverextension

### ISSUE THREAD

**Issue by javadba** [jupyter-incubator/sparkmagic#323]
I successfully invoked the following:

pip install sparkmagic
pip show sparkmagic
jupyter-kernelspec install sparkmagic/kernels/sparkkernel
jupyter-kernelspec install sparkmagic/kernels/pysparkkernel
jupyter-kernelspec install sparkmagic/kernels/pyspark3kernel
jupyter-kernelspec install sparkmagic/kernels/sparkrkernel

But when running : 

 jupyter serverextension enable --py sparkmagic

There is a long stack trace at the end of which we see 

      ModuleNotFoundError: No module named 'sparkmagic'

Here is full stacktrace:

$ jupyter serverextension enable --py sparkmagic
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-serverextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/site-packages/notebook/serverextensions.py", line 300, in start
    super(ServerExtensionApp, self).start()
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python3.6/site-packages/notebook/serverextensions.py", line 217, in start
    self.toggle_server_extension_python(arg)
  File "/usr/local/lib/python3.6/site-packages/notebook/serverextensions.py", line 206, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/usr/local/lib/python3.6/site-packages/notebook/serverextensions.py", line 334, in _get_server_extension_metadata
    m = import_item(module)
  File "/usr/local/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])

In addition:  I am unable to load the sparkmagic inside ipython. 

$ipython
Python 2.7.12 (default, Oct 11 2016, 05:24:00)
IPython 4.2.1 -- An enhanced Interactive Python.

In [1]: %load_ext sparkmagic.magics

There is a very long stacktrace that includes in the middle:

/usr/local/lib/python2.7/site-packages/IPython/core/extensions.pyc in _call_load_ipython_extension(self, mod)
    131     def _call_load_ipython_extension(self, mod):
    132         if hasattr(mod, 'load_ipython_extension'):
--> 133             mod.load_ipython_extension(self.shell)
    134             return True
    135

/usr/local/lib/python2.7/site-packages/sparkmagic/magics/remotesparkmagics.pyc in load_ipython_extension(ip)
    186
    187 def load_ipython_extension(ip):
--> 188     ip.register_magics(RemoteSparkMagics)

So what step(s) am I missing ?  Thanks

**Comment by aggFTW** [comment]
What does `pip show sparkmagic` show?

And what are the actual exceptions in the stacktraces?

**Comment by javadba** [comment]
The issue was jupyterhub had moved jupyter from 2.7 to 3.6  . it was difficult to diagnose and even more difficult to fix: uninstalling jupyterhub did not resolve. I needed to  `pip --force-reinstall` on ipython, jupyter and also did sparkmagic.

**Comment by aggFTW** [comment]
I don't quite understand what happened with the information given, but I'm happy you resolved your issue.
