### ISSUE TITLE
Issue with Spark kernel (hive table)

### ISSUE THREAD

**Issue by daithang1111** [jupyter-incubator/sparkmagic#340]
Hi,
I am running this command, and it works:
```
%%sql -o query1
create external table if not exists test(idd int, name string)
row format delimited fields terminated by ',' lines terminated by '\n'
stored as textfile location 'test'
```
, however this
```
select * from test
```
doesn't work. The error is very consistent for 'select', 'insert'...

```
An error was encountered:
org.apache.spark.sql.AnalysisException:
Hive support is required to insert into the following tables:
`default`.`test`
               ;;
'InsertIntoTable 'SimpleCatalogRelation default, CatalogTable(
	Table: `default`.`test`
	Created: Thu Mar 09 04:49:22 UTC 2017
	Last Access: Wed Dec 31 23:59:59 UTC 1969
	Type: EXTERNAL
	Schema: [StructField(idd,IntegerType,true), StructField(name,StringType,true)]
	Provider: hive
	Storage(Location: test, InputFormat: org.apache.hadoop.mapred.TextInputFormat, OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat, Properties: [field.delim=,, serialization.format=,, line.delim=
])), OverwriteOptions(false,Map()), false
+- LocalRelation [col1#6, col2#7]

  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.failAnalysis(CheckAnalysis.scala:40)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.failAnalysis(Analyzer.scala:57)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:383)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:67)
  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:128)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:67)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:57)
  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:48)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:63)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:592)
  ... 47 elided

```

I have been googling for a while, but no hope. Please help!
PS: I am running Livy using Marathon on aws, Spark2.1.0.

**Comment by aggFTW** [comment]
This is a Spark question, not a sparkmagic question. I'd ask that you please seek help in Spark help forums. Closing.

**Comment by b11z** [comment]
I was getting the "Hive support is required" error, in the end the culprit was livy -- tweaking the `livy.repl.enable-hive-context` configuration fixed it.

(This ticket is long dead, but I figured it might be helpful to leave the solution here.)
