### ISSUE TITLE
pip install sparkmagic throws OSError: [Errno 13] Permission denied: '/usr/local/man'

### ISSUE THREAD

**Issue by asmaier** [jupyter-incubator/sparkmagic#380]
On Mac OS X 10.12.5 with python 2.7 installed with homebrew I get the following error message at the end of the installation 

```
$ pip install sparkmagic
...
Successfully built sparkmagic hdijupyterutils autovizwidget tornado plotly simplegeneric terminado pykerberos MarkupSafe pandocfilters scandir functools32 configparser
Installing collected packages: gnureadline, backports.shutil-get-terminal-size, six, scandir, pathlib2, pickleshare, simplegeneric, decorator, ptyprocess, pexpect, ipython-genutils, enum34, traitlets, appnope, ipython, nose, funcsigs, pbr, mock, singledispatch, certifi, backports-abc, tornado, MarkupSafe, jinja2, terminado, functools32, jsonschema, jupyter-core, nbformat, pyzmq, python-dateutil, jupyter-client, mistune, configparser, entrypoints, pandocfilters, pygments, webencodings, html5lib, bleach, testpath, nbconvert, ipykernel, notebook, widgetsnbextension, ipywidgets, wcwidth, prompt-toolkit, jupyter-console, qtconsole, jupyter, numpy, pytz, pandas, hdijupyterutils, chardet, urllib3, idna, requests, plotly, autovizwidget, pykerberos, requests-kerberos, sparkmagic
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/man'
```

**Comment by asmaier** [comment]
My workaround was to run `pip install sparkmagic` a second time.

**Comment by aggFTW** [comment]
This seems like a folder permission issue not related to sparkmagic itself. I don't have a Mac... is there anyone else who can verify?

**Comment by itamarst** [comment]
This is really old, I'm going to close it.
