### ISSUE TITLE
Livy 0.5.0 

### ISSUE THREAD

**Issue by abronte** [jupyter-incubator/sparkmagic#476]
I recently tried upgrading from AWS EMR version 5.13.0 to 5.16.0 which bumps Livy from 0.4.0 to 0.5.0 and I'm seeing issues in sparkmagic that aren't happening in vanilla spark.

I'm using sparkmagic 0.12.5.

It seems to be around the `sqlContext` object isn't the same anymore. 

When I run this in pyspark is works just fine.
```
[root@ip-10-0-0-32 ~]# pyspark
Python 2.7.14 (default, May  2 2018, 18:31:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
18/08/28 18:50:37 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.3.1
      /_/

Using Python version 2.7.14 (default, May  2 2018 18:31:34)
SparkSession available as 'spark'.
>>> from pyspark.sql import SQLContext
>>> my_sql_context = SQLContext.getOrCreate(sc)
>>> df = my_sql_context.read.parquet('s3://my-bucket/mydata.parquet')
>>> print(df.count())
67556724
```

But the same code executed via jupyter and sparkmagic, I get this.
```
from pyspark.sql import SQLContext
my_sql_context = SQLContext.getOrCreate(sc)
df = my_sql_context.read.parquet('s3://my-bucket/mydata.parquet')
print(df.count())

'JavaMember' object has no attribute 'read'
Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/context.py", line 433, in read
    return DataFrameReader(self)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 70, in __init__
    self._jreader = spark._ssql_ctx.read()
AttributeError: 'JavaMember' object has no attribute 'read'
```

Its the same issue with the default sqlContext object. 
```
df = sqlContext.read.parquet('s3://my-bucket/mydata.parquet')

'JavaMember' object has no attribute 'read'
Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/context.py", line 433, in read
    return DataFrameReader(self)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 70, in __init__
    self._jreader = spark._ssql_ctx.read()
AttributeError: 'JavaMember' object has no attribute 'read'
```

Has anyone else run into this problem? I'm not sure if this is a Livy or sparkmagic issue.

**Comment by abronte** [comment]
After calling the API directly, I've confirmed this is a Livy issue. https://issues.apache.org/jira/browse/LIVY-504
