### ISSUE TITLE
Magics in IPython Kernel - refers to missing hivesampletable

### ISSUE THREAD

**Issue by coaic** [jupyter-incubator/sparkmagic#506]
%%spark -c sql -o df_hvac --maxrows 10
SELECT * FROM hivesampletable

Returns:

An error was encountered:
u'Table or view not found: hivesampletable; line 1 pos 14'
Traceback (most recent call last):
  File "/usr/spark-2.1.0/python/lib/pyspark.zip/pyspark/sql/session.py", line 541, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
  File "/usr/spark-2.1.0/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/spark-2.1.0/python/lib/pyspark.zip/pyspark/sql/utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
AnalysisException: u'Table or view not found: hivesampletable; line 1 pos 14'

**Comment by itamarst** [comment]
I've removed some of the references, but the notebooks need to remove all the references to that, yeah.
