### ISSUE TITLE
PySpark kernel failed caused by Py4j, while Python3 kernel with manually started pyspark shell works well.

### ISSUE THREAD

**Issue by ftune** [jupyter-incubator/sparkmagic#597]
Running on spark on docker. Ports opend like this
```
    expose:
      - 4040
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
      - 8998
      - 8990
      - 25333
```
ENV info:
```
Python 3.7.4
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.3.0
      /_/

Using Python version 3.7.4 (default, Aug 13 2019 20:35:49)
SparkSession available as 'spark'.
```

PySpark kernel failed at start, while Spark and Python3 or even pyspark shell works well.
Pyspark report a fatal error:
```
The code failed because of a fatal error:
	Session 0 unexpectedly reached final status 'error'. See logs:
stdout: 
2019-12-04 05:13:51 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-12-04 05:13:51 INFO  RSCDriver:160 - Connecting to: master:10000
2019-12-04 05:13:51 INFO  RSCDriver:182 - Starting RPC server...
2019-12-04 05:13:51 INFO  RpcServer:105 - Connected to the port 10001
2019-12-04 05:13:51 WARN  RSCConf:146 - Your hostname, master, resolves to a loopback address, but we couldn't find any external IP address!
2019-12-04 05:13:51 WARN  RSCConf:148 - Set livy.rsc.rpc.server.address if you need to bind to another address.
2019-12-04 05:13:52 INFO  RSCDriver:409 - Received job request aa2d0226-b4f6-44d9-9956-ed9b7fa3739d
2019-12-04 05:13:52 INFO  RSCDriver:369 - SparkContext not yet up, queueing job request.
2019-12-04 05:13:55 INFO  SparkEntries:52 - Starting Spark context...
2019-12-04 05:13:55 INFO  SparkContext:54 - Running Spark version 2.3.0
2019-12-04 05:13:55 INFO  SparkContext:54 - Submitted application: livy-session-0
2019-12-04 05:13:55 INFO  SecurityManager:54 - Changing view acls to: root
2019-12-04 05:13:55 INFO  SecurityManager:54 - Changing modify acls to: root
2019-12-04 05:13:55 INFO  SecurityManager:54 - Changing view acls groups to: 
2019-12-04 05:13:55 INFO  SecurityManager:54 - Changing modify acls groups to: 
2019-12-04 05:13:55 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
2019-12-04 05:13:55 INFO  Utils:54 - Successfully started service 'sparkDriver' on port 45435.
2019-12-04 05:13:55 INFO  SparkEnv:54 - Registering MapOutputTracker
2019-12-04 05:13:55 INFO  SparkEnv:54 - Registering BlockManagerMaster
2019-12-04 05:13:55 INFO  BlockManagerMasterEndpoint:54 - Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
2019-12-04 05:13:55 INFO  BlockManagerMasterEndpoint:54 - BlockManagerMasterEndpoint up
2019-12-04 05:13:55 INFO  DiskBlockManager:54 - Created local directory at /tmp/blockmgr-6be641a4-89f3-4765-b76e-f731feef058e
2019-12-04 05:13:55 INFO  MemoryStore:54 - MemoryStore started with capacity 353.4 MB
2019-12-04 05:13:55 INFO  SparkEnv:54 - Registering OutputCommitCoordinator
2019-12-04 05:13:55 INFO  log:192 - Logging initialized @5539ms
2019-12-04 05:13:55 INFO  Server:346 - jetty-9.3.z-SNAPSHOT
2019-12-04 05:13:55 INFO  Server:414 - Started @5592ms
2019-12-04 05:13:55 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
2019-12-04 05:13:55 INFO  AbstractConnector:278 - Started ServerConnector@32239620{HTTP/1.1,[http/1.1]}{0.0.0.0:4041}
2019-12-04 05:13:55 INFO  Utils:54 - Successfully started service 'SparkUI' on port 4041.
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@3ba4dbe1{/jobs,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6ca68df8{/jobs/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@61841278{/jobs/job,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@78c48fa5{/jobs/job/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@20d51408{/stages,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6103d5b8{/stages/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5ac95300{/stages/stage,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@7100ddb5{/stages/stage/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@61c1d1c6{/stages/pool,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5bb5d2b{/stages/pool/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5145a9{/storage,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@77cbcd63{/storage/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@186b7dbd{/storage/rdd,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4766299e{/storage/rdd/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4d1050d6{/environment,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@64192cc2{/environment/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@27dc2369{/executors,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5180c4d5{/executors/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@1ed9a8d3{/executors/threadDump,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@338be8f6{/executors/threadDump/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@750a4285{/static,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@2474892{/,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@44bec90b{/api,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@72fc65cb{/jobs/job/kill,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6c574c4a{/stages/stage/kill,null,AVAILABLE,@Spark}
2019-12-04 05:13:55 INFO  SparkUI:54 - Bound SparkUI to 0.0.0.0, and started at http://localhost:4041
2019-12-04 05:13:55 INFO  SparkContext:54 - Added JAR file:///usr/livy/apache-livy-0.6.0-incubating-bin/rsc-jars/livy-thriftserver-session-0.6.0-incubating.jar at spark://master:45435/jars/livy-thriftserver-session-0.6.0-incubating.jar with timestamp 1575436435863
2019-12-04 05:13:55 INFO  SparkContext:54 - Added JAR file:///usr/livy/apache-livy-0.6.0-incubating-bin/rsc-jars/netty-all-4.0.37.Final.jar at spark://master:45435/jars/netty-all-4.0.37.Final.jar with timestamp 1575436435863
2019-12-04 05:13:55 INFO  SparkContext:54 - Added JAR file:///usr/livy/apache-livy-0.6.0-incubating-bin/rsc-jars/livy-rsc-0.6.0-incubating.jar at spark://master:45435/jars/livy-rsc-0.6.0-incubating.jar with timestamp 1575436435863
2019-12-04 05:13:55 INFO  SparkContext:54 - Added JAR file:///usr/livy/apache-livy-0.6.0-incubating-bin/rsc-jars/livy-api-0.6.0-incubating.jar at spark://master:45435/jars/livy-api-0.6.0-incubating.jar with timestamp 1575436435864
2019-12-04 05:13:55 INFO  SparkContext:54 - Added JAR file:///usr/livy/apache-livy-0.6.0-incubating-bin/repl_2.11-jars/livy-repl_2.11-0.6.0-incubating.jar at spark://master:45435/jars/livy-repl_2.11-0.6.0-incubating.jar with timestamp 1575436435864
2019-12-04 05:13:55 INFO  SparkContext:54 - Added JAR file:///usr/livy/apache-livy-0.6.0-incubating-bin/repl_2.11-jars/commons-codec-1.9.jar at spark://master:45435/jars/commons-codec-1.9.jar with timestamp 1575436435864
2019-12-04 05:13:55 INFO  SparkContext:54 - Added JAR file:///usr/livy/apache-livy-0.6.0-incubating-bin/repl_2.11-jars/livy-core_2.11-0.6.0-incubating.jar at spark://master:45435/jars/livy-core_2.11-0.6.0-incubating.jar with timestamp 1575436435864
2019-12-04 05:13:55 INFO  Executor:54 - Starting executor ID driver on host localhost
2019-12-04 05:13:55 INFO  Executor:54 - Using REPL class URI: spark://master:45435/classes
2019-12-04 05:13:55 INFO  Utils:54 - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36041.
2019-12-04 05:13:55 INFO  NettyBlockTransferService:54 - Server created on master:36041
2019-12-04 05:13:55 INFO  BlockManager:54 - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2019-12-04 05:13:55 INFO  BlockManagerMaster:54 - Registering BlockManager BlockManagerId(driver, master, 36041, None)
2019-12-04 05:13:55 INFO  BlockManagerMasterEndpoint:54 - Registering block manager master:36041 with 353.4 MB RAM, BlockManagerId(driver, master, 36041, None)
2019-12-04 05:13:55 INFO  BlockManagerMaster:54 - Registered BlockManager BlockManagerId(driver, master, 36041, None)
2019-12-04 05:13:55 INFO  BlockManager:54 - Initialized BlockManager: BlockManagerId(driver, master, 36041, None)
2019-12-04 05:13:56 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@2b694e45{/metrics/json,null,AVAILABLE,@Spark}
2019-12-04 05:13:56 INFO  SparkEntries:55 - Spark context finished initialization in 623ms
2019-12-04 05:13:56 INFO  SparkEntries:86 - Created Spark session.
2019-12-04 05:13:59 WARN  PythonInterpreter$:48 - Fail to create GatewayServer with auth parameter, downgrade to old constructor
java.lang.NoSuchMethodException: py4j.GatewayServer$GatewayServerBuilder.authToken(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1786)
	at org.apache.livy.repl.PythonInterpreter$.createGatewayServer(PythonInterpreter.scala:146)
	at org.apache.livy.repl.PythonInterpreter$.apply(PythonInterpreter.scala:55)
	at org.apache.livy.repl.Session.liftedTree1$1(Session.scala:106)
	at org.apache.livy.repl.Session.interpreter(Session.scala:98)
	at org.apache.livy.repl.Session.org$apache$livy$repl$Session$$setJobGroup(Session.scala:353)
	at org.apache.livy.repl.Session$$anonfun$execute$1.apply$mcV$sp(Session.scala:164)
	at org.apache.livy.repl.Session$$anonfun$execute$1.apply(Session.scala:163)
	at org.apache.livy.repl.Session$$anonfun$execute$1.apply(Session.scala:163)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2019-12-04 05:14:00 ERROR PythonInterpreter:56 - Process has died with 1
2019-12-04 05:14:00 ERROR PythonInterpreter:56 - ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/spark-2.3.0/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1062, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:.

Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
c) Restart the kernel.
```
I try another way to open pyspark in the python3 kernel by 
```
import os
import sys
spark_name = os.environ.get('SPARK_HOME',None)
if not spark_name:
    raise ValueErrorError('spark env error')
sys.path.insert(0,os.path.join(spark_name,'python'))
sys.path.insert(0,os.path.join(spark_name,'python/lib/py4j-0.10.6-src.zip'))
exec(open(os.path.join(spark_name,'python/pyspark/shell.py')).read())
```
Then i find it works???
```
myRDD = sc.parallelize(range(6), 3)
type(myRDD)
out [7]:pyspark.rdd.PipelinedRDD
```
Then I tried spark kernel, it works well too.
Could it be a bug?

**Comment by itamarst** [comment]
Hi, what version of sparkmagic is this?

**Comment by ftune** [comment]
sparkmagic==0.14.0

**Comment by ftune** [comment]
caused by error docker container env and conf.
