### ISSUE TITLE
[BUG] Not working with datamechanics/spark:2.4.7-hadoop-3.1.0-java-8-scala-2.11-python-3.7-latest

### ISSUE THREAD

**Issue by ltregan** [jupyter-incubator/sparkmagic#809]
**Describe the bug**
I believe there was a new push of the image by datamechanics (5 days ago ?) and now sparkmagic docker image does not work anymore. If you log to the spark-1 container, and try ../bin/pyspark I get this error:

			Caused by: java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.1.0
        at org.apache.hadoop.hive.shims.ShimLoader.getMajorVersion(ShimLoader.java:174)
        at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:139)
        at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:100)
        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:368)

**To Reproduce**
git clone https://github.com/jupyter-incubator/sparkmagic sparkmagic-dev
cd sparkmagic-dev
docker compose up

then create a new PySpark notebook and a simple command does not. work. eg. %data = [(1, 'John', 'Doe')]

```
The code failed because of a fatal error:
	Error sending http request and maximum retry encountered..

Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
c) Restart the kernel.
```

**Expected behavior**
PySpark kernel should work

**Screenshots**

**Versions:**
 - SparkMagic 20.4 or master
 - Livy (if you know it)
 - Spark 2.4.7

**Additional context**
I believe there was a new push of the image by datamechanics (5 days ago ?)

**Comment by devstein** [comment]
Hi @ltregan thanks for opening and issue. I'm looking into this today

**Comment by devstein** [comment]
@ltregan I'm unable to reproduce. Can you check if you are still running into issues?

**Comment by ltregan** [comment]
My bad - I tried again after clearing up docker cache and the error disappeared:
  docker system prune -a -f

I face a second challenge that on Mac M1 pyspark does not want to start and consumes 40% CPU (see screenshot), but I should open a separate issue for that.

<img width="1190" alt="Screenshot 2023-03-15 at 7 41 54 PM" src="https://user-images.githubusercontent.com/4487480/225411113-ab8e82dd-90b4-4f8b-b8c0-05b67f0fcbed.png">

**Comment by ltregan** [comment]
Still same issue, even after clearing the cache. Exact sequence is:
```
$ docker system prune -a -f
$ git clone https://github.com/jupyter-incubator/sparkmagic sparkmagic-dev
$ cd sparkmagic-dev
$ docker compose up
```
Adding screenshots in case they help.

Full log below:
```

sh-5.1# ../bin/pyspark
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
23/03/15 18:45:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Exception in thread "Thread-4" java.lang.ExceptionInInitializerError
        at org.apache.hadoop.hive.conf.HiveConf.<clinit>(HiveConf.java:105)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at py4j.reflection.CurrentThreadClassLoadingStrategy.classForName(CurrentThreadClassLoadingStrategy.java:40)
        at py4j.reflection.ReflectionUtil.classForName(ReflectionUtil.java:51)
        at py4j.reflection.TypeUtil.forName(TypeUtil.java:243)
        at py4j.commands.ReflectionCommand.getUnknownMember(ReflectionCommand.java:175)
        at py4j.commands.ReflectionCommand.execute(ReflectionCommand.java:87)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.1.0
        at org.apache.hadoop.hive.shims.ShimLoader.getMajorVersion(ShimLoader.java:174)
        at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:139)
        at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:100)
        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:368)
        ... 10 more
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.7
      /_/

Using Python version 3.7.11 (default, Jul 27 2021 14:32:16)
SparkSession available as 'spark'.
>>> 
```
<img width="1190" alt="Screenshot 2023-03-15 at 7 45 27 PM" src="https://user-images.githubusercontent.com/4487480/225412853-17f04cdf-9722-4ed8-bbcf-80ac14076dbc.png">
<img width="1190" alt="Screenshot 2023-03-15 at 7 45 36 PM" src="https://user-images.githubusercontent.com/4487480/225412859-d20bd768-e0e2-4bc7-9127-30ab3a108aee.png">
<img width="1190" alt="Screenshot 2023-03-15 at 7 45 45 PM" src="https://user-images.githubusercontent.com/4487480/225412861-1378b0b0-2389-4b9b-aa1a-80e1e21c9389.png">
